[tool.poetry]
name = "robotv4"
version = "0.1.0"
description = "AI Chatbot with DeFi capabilities"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"  # Updated Python version requirement for langchain compatibility
langchain = "^0.0.330"
openai = "^1.2.0"
python-dotenv = "^1.0.0"
requests = "^2.31.0"
google-search-results = "^2.4.2"
python-docx = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"