[tool.poetry]
name = "document-aware-chatbot"
version = "0.1.0"
description = "AI Chatbot with document processing capabilities"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
streamlit = "^1.24.0"
langchain = "^0.0.330"
chromadb = "^0.3.0"
python-dotenv = "^1.0.0"
requests = "^2.31.0"
pillow = "^8.2.0"
pypdf = "^3.0.0"
ollama = "^0.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
black = "^23.0.0"
isort = "^5.12.0"
mypy = "^1.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3