[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "ollama-chatbot"
version = "0.1.0"
authors = [
  {name="Your Name", email="your.email@example.com"},
]
description = "Streamlit chatbot powered by Ollama"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.dependencies]
streamlit = "^1.28.0"
requests = "^2.31.0"
python-dotenv = "^1.0.0"
langchain = "^0.0.340"
langchain-community = "^0.0.11"
gTTS = "^2.3.2"
pytz = "^2023.3"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=23.0",
    "flake8>=6.0",
]