name: Core Functionality Test

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install minimum requirements
      run: |
        python -m pip install --upgrade pip
        pip install streamlit
    - name: Verify app structure
      run: |
        python -c "from app import OllamaChat; print('✅ Core component imports work')"