name: OS Smoke Test

on: [push, pull_request]

jobs:
  smoke-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Verify basic functionality
      run: |
        python -c "import streamlit; print('Streamlit imports successfully')"
        python -c "from app import main; print('Main function imports successfully')"